server:
  port: 8080
spring:
  application:
    name: takeaway
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hotel?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root0811

#  RabbitMQ 基础配置
  rabbitmq:
    host: 192.168.0.118 # 地址
    port: 5672 # 端口号
    username: admin #用户名
    password: admin #密码
    virtual-host: /
    listener:
      simple:
        prefetch: 1 #设置prefetch 控制欲取消息 上限


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


